### ISSUE TITLE
Change default branch to fpm

### ISSUE THREAD

**Issue by awvwgk** [ivan-pi/kdtree2#11]
The current default branch is the original master branch. Would it be possible to have the fpm branch as default branch to make it show up upon visiting this repository?

**Comment by ivan-pi** [comment]
Of course. I wanted to update the README first, but it is better any potential collaborators land directly on the fpm branch first. Apart from the TOML file, I performed a few other commits. The biggest one being to remove the C++ files (I don't think these are relevant anymore - besides perhaps for benchmarking...) and split the old monolithic module file into three files.

I will also rename the former "master" to something like "original" or "archive".
